# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

target 'BZCarousel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BZCarousel

end

target 'Playground' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Playground

end
